const net = require('net');
const WebSocket = require('ws');
const https = require('https');
const http  = require('http');
const fs = require('fs');
const { exec } = require('child_process');

const AUDIOSOCKET_PORT  = 9092;
const KOTHABOT_WSS_URL  = process.env.KOTHABOT_WSS_URL  || 'wss://voice-server.up.railway.app';
const KOTHABOT_WEB_URL  = process.env.KOTHABOT_WEB_URL  || 'https://my.kothabot.ai.bd';
const GATEWAY_TOKEN     = process.env.GATEWAY_TOKEN     || 'kothabot-voip-secret-token-2026';

// 20ms silence at 8kHz/16-bit = 320 bytes
const FRAME_SIZE    = 320;
const SILENCE_FRAME = Buffer.alloc(FRAME_SIZE, 0);

function makeFrame(pcm) {
  const h = Buffer.alloc(3);
  h.writeUInt8(0x10, 0);
  h.writeUInt16BE(pcm.length, 1);
  return Buffer.concat([h, pcm]);
}
const SILENCE_PACKET = makeFrame(SILENCE_FRAME); // pre-built

function bufferToUuid(buf) {
  if (buf.length !== 16) return null;
  const h = buf.toString('hex');
  return [h.slice(0,8),h.slice(8,12),h.slice(12,16),h.slice(16,20),h.slice(20)].join('-');
}

function upscale8To24(buffer) {
  const ab  = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  const src = new Int16Array(ab);
  const dst = new Int16Array(src.length * 3);
  for (let i = 0; i < src.length; i++) dst[i*3] = dst[i*3+1] = dst[i*3+2] = src[i];
  return Buffer.from(dst.buffer, dst.byteOffset, dst.byteLength);
}

function downscale24To8(buffer) {
  const ab  = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  const src = new Int16Array(ab);
  const dst = new Int16Array(Math.floor(src.length / 3));
  for (let i = 0; i < dst.length; i++) dst[i] = Math.round((src[i*3]+src[i*3+1]+src[i*3+2])/3);
  return Buffer.from(dst.buffer, dst.byteOffset, dst.byteLength);
}

// ── Shop config cache — loaded on startup, refreshed every 5 min ─────────────
let shopCache = {}; // { [shopId]: configObject }

function loadShopConfigs() {
  return new Promise((resolve) => {
    const url    = `${KOTHABOT_WEB_URL}/api/voice/telephony-sync`;
    const parsed = new URL(url);
    const agent  = parsed.protocol === 'https:' ? https : http;
    const req = agent.request({
      hostname: parsed.hostname,
      port:     parsed.port || (parsed.protocol === 'https:' ? 443 : 80),
      path:     parsed.pathname,
      method:   'GET',
      headers:  { 'Authorization': `Bearer ${GATEWAY_TOKEN}` },
      timeout:  8000,
    }, (res) => {
      let body = '';
      res.on('data', c => body += c);
      res.on('end', () => {
        try {
          const json = JSON.parse(body);
          const newCache = {};
          for (const shop of (json.shops || [])) {
            newCache[shop.shopId] = shop;
          }
          shopCache = newCache;
          console.log(`[config] Loaded ${Object.keys(shopCache).length} shop(s):`, Object.values(shopCache).map(s => s.shopName || s.shopId).join(', '));
        } catch (e) { console.error('[config] Parse error:', e.message); }
        resolve();
      });
    });
    req.on('error', (e) => { console.error('[config] Fetch error:', e.message); resolve(); });
    req.on('timeout', () => { req.destroy(); resolve(); });
    req.end();
  });
}

// Refresh every 5 minutes
setInterval(loadShopConfigs, 5 * 60 * 1000);

let lastSipIps = null;

function syncSystemConfig() {
  const url = `${KOTHABOT_WEB_URL}/api/voice/system-config`;
  const parsed = new URL(url);
  const agent = parsed.protocol === 'https:' ? https : http;
  const req = agent.request({
    hostname: parsed.hostname,
    port: parsed.port || (parsed.protocol === 'https:' ? 443 : 80),
    path: parsed.pathname,
    method: 'GET',
    headers: { 'Authorization': `Bearer ${GATEWAY_TOKEN}` },
    timeout: 8000,
  }, (res) => {
    let body = '';
    res.on('data', c => body += c);
    res.on('end', () => {
      try {
        const json = JSON.parse(body);
        const newIps = json.sipIps || [];
        const newIpsStr = newIps.slice().sort().join(',');
        
        if (lastSipIps !== newIpsStr) {
          lastSipIps = newIpsStr;
          console.log(`[config] SIP IPs changed: ${newIpsStr}`);
          
          let conf = '; Auto-generated by KothaBot Bridge\\n\\n';
          newIps.forEach((ip, idx) => {
            conf += `[provider-endpoint-${idx}]\\n`;
            conf += `type=endpoint\\n`;
            conf += `context=kothabot-incoming\\n`;
            conf += `disallow=all\\n`;
            conf += `allow=ulaw,alaw\\n`;
            conf += `aors=provider-aor-${idx}\\n\\n`;
            
            conf += `[provider-aor-${idx}]\\n`;
            conf += `type=aor\\n`;
            conf += `contact=sip:${ip}:5060\\n\\n`;
            
            conf += `[provider-identify-${idx}]\\n`;
            conf += `type=identify\\n`;
            conf += `endpoint=provider-endpoint-${idx}\\n`;
            conf += `match=${ip}\\n\\n`;
          });
          
          const confPath = process.env.PJSIP_CUSTOM_CONF || '/opt/kothabot/asterisk-config/pjsip_custom.conf';
          fs.writeFileSync(confPath, conf);
          console.log(`[config] Wrote ${confPath}, reloading Asterisk...`);
          exec("docker exec asterisk-server asterisk -rx 'core reload'", (err) => {
            if (err) console.error('[config] Asterisk reload failed:', err.message);
            else console.log('[config] Asterisk reloaded successfully.');
          });
        }
      } catch (e) { console.error('[config] Parse error system-config:', e.message); }
    });
  });
  req.on('error', (e) => console.error('[config] Fetch system-config error:', e.message));
  req.on('timeout', () => { req.destroy(); });
  req.end();
}

setInterval(syncSystemConfig, 60 * 1000);

// ── TCP Server (Asterisk AudioSocket) ────────────────────────────────────────
const tcpServer = net.createServer((socket) => {
  console.log('[bridge] 📞 Incoming call');

  // IMMEDIATELY flood 500ms silence so Asterisk poll timer doesn't expire
  for (let i = 0; i < 25; i++) socket.write(SILENCE_PACKET);

  let ws         = null;
  let wsReady    = false;
  let inBuf      = Buffer.alloc(0);
  let pendingAudio = [];
  let playoutBuf = Buffer.alloc(0);
  let lastWriteTime = Date.now();
  let nextPlayoutTime = Date.now();
  let silenceStartMs = 0;

  function playNextFrame() {
    if (socket.destroyed) return;
    const now = Date.now();
    
    // Catch up if we fell behind, but don't burst more than 3 frames at once to prevent RTP overflow
    let framesSent = 0;
    while (now >= nextPlayoutTime && framesSent < 3) {
      if (playoutBuf.length >= FRAME_SIZE) {
        socket.write(makeFrame(playoutBuf.subarray(0, FRAME_SIZE)));
        playoutBuf = playoutBuf.subarray(FRAME_SIZE);
        lastWriteTime = now;
      } else {
        // Send silence if no AI audio to keep connection alive
        if (now - lastWriteTime >= 20) {
          socket.write(SILENCE_PACKET);
          lastWriteTime = now;
        }
      }
      nextPlayoutTime += 20;
      framesSent++;
    }
    
    // If we fell way behind (e.g. event loop blocked), reset the clock to avoid massive bursts
    if (now > nextPlayoutTime + 100) {
      nextPlayoutTime = now;
    }
    
    setTimeout(playNextFrame, Math.max(1, nextPlayoutTime - Date.now()));
  }
  playNextFrame();

  function initSession(didOrShopId) {
    // Find shop by DID (number) or fallback to shopId
    let shopConfig = shopCache[didOrShopId]; // direct hit by ID
    if (!shopConfig) {
      for (const shop of Object.values(shopCache)) {
        if (shop.number === didOrShopId) {
          shopConfig = shop;
          break;
        }
      }
    }
    
    if (!shopConfig) {
      console.warn(`[bridge] ⚠️ No shop found for DID/ID: ${didOrShopId}. Using fallback config.`);
      shopConfig = { shopId: didOrShopId, language: 'auto', voice: 'Aoede' };
    }
    const shopId = shopConfig.shopId;
    console.log(`[bridge] Shop: "${shopConfig.shopName || shopId}" | Lang: ${shopConfig.language}`);

    ws = new WebSocket(KOTHABOT_WSS_URL, { headers: { Origin: 'http://localhost' } });

    ws.on('open', () => {
      console.log('[bridge] Cloud WS connected — sending START_SESSION');
      ws.send(JSON.stringify({
        type: 'START_SESSION',
        shopId,
        config: {
          shopId,
          shopName:        shopConfig.shopName        || '',
          systemPrompt:    shopConfig.systemPrompt    || '',
          greetingMessage: shopConfig.greetingMessage || '',
          trainingData:    shopConfig.trainingData    || '',
          language:        shopConfig.language        || 'auto',
          voice:           shopConfig.voice           || 'Aoede',
          aiModel:         shopConfig.aiModel         || '',
          category:        shopConfig.category        || '',
          collectFields:   shopConfig.collectFields   || { name: true, phone: true, address: true },
        }
      }));
    });

    ws.on('message', (data) => {
      try {
        const msg = JSON.parse(data.toString());
        if (msg.type === 'SESSION_READY') {
          wsReady = true;
          console.log(`[bridge] ✅ AI ready — flushing ${pendingAudio.length} buffered chunks`);
          for (const chunk of pendingAudio)
            ws.send(JSON.stringify({ type: 'AUDIO_CHUNK', data: chunk.toString('base64') }));
          pendingAudio = [];
        } else if (msg.type === 'AUDIO_CHUNK') {
          // Add to playout buffer so the precise timer can pace it to Asterisk
          const pcm8 = downscale24To8(Buffer.from(msg.data, 'base64'));
          if (playoutBuf.length + pcm8.length <= FRAME_SIZE * 400) // 8s cap
            playoutBuf = Buffer.concat([playoutBuf, pcm8]);
        } else if (msg.type === 'END_SESSION') {
          console.log('[bridge] 🛑 AI ended session — hanging up call');
          socket.end(); // Clean TCP FIN to signal Asterisk to hang up
        }
      } catch {}
    });

    ws.on('close', () => { console.log('[bridge] Cloud WS closed'); socket.end(); });
    ws.on('error', (e) => console.error('[bridge] WS error:', e.message));
  }

  socket.on('data', (chunk) => {
    inBuf = Buffer.concat([inBuf, chunk]);
    while (inBuf.length >= 3) {
      const type   = inBuf.readUInt8(0);
      const length = inBuf.readUInt16BE(1);
      if (inBuf.length < 3 + length) break;
      const payload = inBuf.slice(3, 3 + length);
      inBuf         = inBuf.slice(3 + length);

      if (type === 0x01) {
        const rawUuid = bufferToUuid(payload);
        if (rawUuid) {
          // UUID format e.g. 00000000-0000-0000-0000-09617854561 -> 09617854561
          const did = rawUuid.replace(/-/g, '').replace(/^0+/, '');
          initSession(did || rawUuid);
        } else { console.error('[bridge] Bad UUID'); socket.destroy(); }
      } else if (type === 0x10 && length > 0) {
        // Calculate energy of 16-bit PCM payload for noise gate
        const src = new Int16Array(payload.buffer.slice(payload.byteOffset, payload.byteOffset + payload.byteLength));
        let energy = 0;
        for (let i = 0; i < src.length; i++) energy += Math.abs(src[i]);
        energy /= src.length;

        const isSilent = energy < 150; // Threshold
        const now = Date.now();

        if (isSilent) {
          if (silenceStartMs === 0) silenceStartMs = now;
        } else {
          silenceStartMs = 0;
        }

        const pcm24 = upscale8To24(payload);
        let audioToSend = pcm24;

        // If silence > 500ms, send zeroed audio
        if (silenceStartMs > 0 && (now - silenceStartMs) > 500) {
          audioToSend = Buffer.alloc(pcm24.length, 0); // Send pure digital silence
        }

        if (wsReady && ws?.readyState === WebSocket.OPEN)
          ws.send(JSON.stringify({ type: 'AUDIO_CHUNK', data: audioToSend.toString('base64') }));
        else if (ws)
          pendingAudio.push(audioToSend);
      }
    }
  });

  socket.on('close', () => {
    console.log('[bridge] 📴 Call ended');
    if (ws?.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify({ type: 'END_SESSION' }));
      ws.close();
    }
  });

  socket.on('error', (e) => { console.error('[bridge] Socket error:', e.message); });
});

// ── Start: load config first, THEN open TCP port ──────────────────────────────
console.log(`[config] Fetching shop configs from ${KOTHABOT_WEB_URL}...`);
console.log(`[config] Fetching shop configs from ${KOTHABOT_WEB_URL}...`);
Promise.all([loadShopConfigs(), syncSystemConfig()]).then(() => {
  tcpServer.listen(AUDIOSOCKET_PORT, '0.0.0.0', () => {
    console.log(`🎙️  KothaBot Bridge listening on :${AUDIOSOCKET_PORT}`);
    console.log(`   Voice Server : ${KOTHABOT_WSS_URL}`);
    console.log(`   Config API   : ${KOTHABOT_WEB_URL}`);
  });
});
